# Generated by Django 6.0.6 on 2026-07-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_rename_titel_course_title_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="notes/"),
        ),
    ]
